services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/eventhub?schema=public
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eventhub-network

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eventhub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventhub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  eventhub-network:
    driver: bridge
